### ISSUE TITLE
我在项目中遇见了这个问题 Unexpected token 'export'

### ISSUE THREAD

**Issue by zhaorui2000** [wzhudev/redi#24]
<img width="1221" alt="image" src="https://github.com/wzhudev/redi/assets/49807887/0b885815-0094-4bd2-bdc9-edef63fe9ae3">

**Comment by wzhudev** [comment]
这和你设置编译工具链的方式有关，似乎你的编译工具并不支持 esm，但是它也没有引用 redi 内部提供的 UMD 包。

请提供一个能重现此问题的最小复现。

**Comment by zhaorui2000** [comment]
> 这和你设置编译工具链的方式有关，似乎你的编译工具并不支持 esm，但是它也没有引用 redi 内部提供的 UMD 包。
> 
> 请提供一个能重现此问题的最小复现。

https://stackblitz.com/edit/withastro-astro-smrbpt

**Comment by wzhudev** [comment]
有一些 package.json 设置不符合 lint，下个版本会修复 https://publint.dev/@wendellhu/redi@0.16.0

**Comment by jikkai** [comment]
> > 这和你设置编译工具链的方式有关，似乎你的编译工具并不支持 esm，但是它也没有引用 redi 内部提供的 UMD 包。
> > 请提供一个能重现此问题的最小复现。
> 
> https://stackblitz.com/edit/withastro-astro-smrbpt

客户端脚本不是在 frontmatter 中运行的，请仔细阅读 astro 文档 https://docs.astro.build/zh-cn/guides/client-side-scripts/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%84%9A%E6%9C%AC
