### ISSUE TITLE
异步依赖项的设计是如何考虑的呢

### ISSUE THREAD

**Issue by hehos** [wzhudev/redi#30]
<img width="661" alt="image" src="https://github.com/user-attachments/assets/3ce4e26c-38ad-4f84-92a2-1c4f01f40328">
这样的设计是处于什么考虑呢？为什么要这样加上一个标识呢？
<img width="701" alt="image" src="https://github.com/user-attachments/assets/b5caf4ea-2917-40b6-9f17-da9bc6a2d061">
为什么不这样直接一点呢？

**Comment by wzhudev** [comment]
你给的代码案例似乎并不完整，没看出来如何调用方应该如何消费这个 BBLoader1
